version: 2
jobs:
  build:
    working_directory: ~/grasp
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sudo npm install -g npm
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      - run:
          name: flow
          command: npm run flow
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
      # - store_test_results:
      #     path: test-results.xml
